name:                tictactoe
version:             0.8
github:              "busyhedg03/tictactoe"
license:             BSD3
author:              "A.Grishchenko"
maintainer:          "agrishchenko1@g.nsu.ru"
copyright:           "2022 A.Grishchenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tictactoe#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- random
- mtl
- time

library:
  source-dirs: src

executables:
  tictactoe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tictactoe

tests:
  tictactoe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tictactoe
